name: Post QoTD
on:
  schedule:
    # https://crontab.guru/#59_15_*_*_*
    - cron: "59 15 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    if: github.repository == 'OfficialPawBot/language'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run lint-qotds && (npm run post-qotd -- --test)
      - run: |
          git config user.name "Paw Bot"
          git config user.email "developers@paw.bot"
      - run: |
          git add data/qotds.json
          (git commit -m 'chore: 🤖 update qotd microdata' && git push) || echo "nothing to commit"